const Question = require("../models/questionModel");
const genAI = require("../config/gemini");

exports.getHint = async (req, res) => {
  try {
    const { question_id } = req.body;

    if (!question_id) {
      return res.status(400).json({
        success: false,
        message: "question_id is required",
      });
    }

    const question = await Question.findOne({ question_id });

    if (!question) {
      return res.status(404).json({
        success: false,
        message: "Question not found",
      });
    }

    const gptQuery = `
        You are a SQL learning assistant.

        STRICT RULES:
        1. NEVER provide the full SQL query.
        2. NEVER provide exact SELECT statement.
        3. NEVER provide final solution.
        4. Provide only conceptual hints.
        5. Maximum 3 hints.
        6. Each hint must be under 20 words.
        7. Do not use code blocks.
        8. Do not mention specific column values unless necessary.

        Return response ONLY in this format:

        
        <hint 1>, <hint 2>, <hint 3>

        QUESTION:
        ${question.question_description}`;

    const result = await genAI.models.generateContent({
      model: "gemini-2.5-flash",
      contents: gptQuery,
    });

    // Extract text safely
    const text = result?.candidates?.[0]?.content?.parts?.[0]?.text || "";

    if (!text) {
      throw new Error("No hint generated by AI.");
    }
    const s=text.split(',');
    return res.json({
      success: true,
      hints: s,
    });
  } catch (error) {
    console.error("Hint Error:", error);
    return res.status(500).json({
      success: false,
      message: "Hint generation failed",
      error: error.message,
    });
  }
};
